#!/bin/sh
bspc rule -r "*"

###---Autostart---###
sxhkd &
nm-applet &
pasystray &
xfce4-power-manager &
picom -b --experimental-backends &
xsetroot -cursor_name left_ptr &
feh --bg-fill $HOME/wallpaper/treesunset.png &
$HOME/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

###---MONITORS---###
bspc monitor HDMI-0 -d 1 2 3 4
bspc monitor DP-4 -d 5 6 7 8

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config single_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#b5e8e0"
bspc config focused_border_color "#e8a2af"

###---Monitor And Desktop Settings----###
bspc config top_padding 25
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 5

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a zoom state=floating center=on follow=on border=off
